// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.user", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("user_avatar");

                    b.Property<DateTime>("user_birthday");

                    b.Property<DateTime?>("user_created_at");

                    b.Property<int>("user_created_by");

                    b.Property<string>("user_email")
                        .IsRequired();

                    b.Property<string>("user_firstname")
                        .IsRequired();

                    b.Property<int>("user_gender");

                    b.Property<int>("user_isdeleted");

                    b.Property<string>("user_lastname")
                        .IsRequired();

                    b.Property<string>("user_password")
                        .IsRequired();

                    b.Property<string>("user_phone")
                        .IsRequired();

                    b.Property<int>("user_status");

                    b.Property<string>("user_token");

                    b.Property<DateTime?>("user_updated_by");

                    b.Property<string>("user_username")
                        .IsRequired();

                    b.HasKey("user_id");

                    b.ToTable("user","dbo");

                    b.HasData(
                        new { user_id = 1, user_birthday = new DateTime(2021, 4, 29, 11, 16, 32, 267, DateTimeKind.Local), user_created_at = new DateTime(2021, 4, 29, 11, 16, 32, 266, DateTimeKind.Local), user_created_by = 1, user_email = "nttung@gmai.com", user_firstname = "Tung", user_gender = 1, user_isdeleted = 0, user_lastname = "Nguyen", user_password = "nttung", user_phone = "096431808", user_status = 1, user_username = "nttung" },
                        new { user_id = 2, user_birthday = new DateTime(2021, 4, 29, 11, 16, 32, 267, DateTimeKind.Local), user_created_at = new DateTime(2021, 4, 29, 11, 16, 32, 267, DateTimeKind.Local), user_created_by = 1, user_email = "abc@gmai.com", user_firstname = "abc", user_gender = 1, user_isdeleted = 0, user_lastname = "abc", user_password = "abc", user_phone = "096431808", user_status = 1, user_username = "abc" },
                        new { user_id = 3, user_birthday = new DateTime(2021, 4, 29, 11, 16, 32, 267, DateTimeKind.Local), user_created_at = new DateTime(2021, 4, 29, 11, 16, 32, 267, DateTimeKind.Local), user_created_by = 1, user_email = "xyz@gmai.com", user_firstname = "xyz", user_gender = 1, user_isdeleted = 0, user_lastname = "xyz", user_password = "xyz", user_phone = "096431808", user_status = 1, user_username = "xyz" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
